# Build customization
builds:
  - main: ./main.go
    binary: go-switch
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

# Archive customization
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

# Checksum customization
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Changelog customization
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Release customization
release:
  github:
    owner: lemon956
    name: go-switch
